### ISSUE TITLE
Random disconnect from msband

### ISSUE THREAD

**Issue by sean369see** [ctpc/nucoach-issues#19]
This is most likely related to the official MS BAND app but we need more people to test the band to deephealth connection.

**Comment by imana97** [comment]
@way2sky : how is it going?
can you give a more detailed update on this?

**Comment by sean369see** [comment]
I am testing the 9th watch. So far still having random disconnects. I 
shouldn't be the only one testing them however.

**Comment by sean369see** [comment]
You can also check hook logs for stress detection module to see when 
disconnections happen. After I am done today with testing two more 
bands, we need to do high traffic testing with many people wearing at 
the same time.

**Comment by imana97** [comment]
@Navarjun : do we have the same problem in the ios app?

**Comment by Navarjun** [comment]
I don't think so… Once it is connected, it pretty much stays connected
