### ISSUE TITLE
Idea for action plans

### ISSUE THREAD

**Issue by cmgordon** [ctpc/nucoach-issues#2]
Currently we can shift days, but could we shift start time (i.e. hour/min)?

**Comment by imana97** [comment]
Solved in the last version.
<img width="881" alt="screen shot 2017-07-21 at 3 02 00 pm" src="https://user-images.githubusercontent.com/586992/28478247-9783b594-6e25-11e7-9e07-71579abeff1f.png">

click on the blue link to change the date. Use with caution.
