### ISSUE TITLE
idea: participant status

### ISSUE THREAD

**Issue by cmgordon** [ctpc/nucoach-issues#26]
Can we create something to indicate participant status on the project page? This will help us filter out participants that we don't need to monitor anymore.
e.g. Planned, Active, Completed, Dropped, Consented but not active

**Comment by imana97** [comment]
@cmgordon done!
<img width="1898" alt="screen shot 2017-09-19 at 2 01 04 pm" src="https://user-images.githubusercontent.com/586992/30607440-071d6f3e-9d43-11e7-885a-673eb36f016e.png">
