### ISSUE TITLE
VERY IMPORTANT

### ISSUE THREAD

**Issue by imana97** [ctpc/nucoach-issues#30]
Hi,
when sending the band data to parse server from the ios app,

please add a role the acl.

so, the js version would be:

```
var acl =new Parse.ACL(Parse.User.current());
acl.setRoleReadAccess('MS_BAND2_sensor_dump',true);

xxxx.setACL(acl);
```

this is very important, let's add this asp.

**Comment by Navarjun** [comment]
Added the code…
Testing from backend pending.
