### ISSUE TITLE
Upload AHM pictures to NUCoach

### ISSUE THREAD

**Issue by cmgordon** [ctpc/nucoach-issues#36]

**Comment by imana97** [comment]
you can upload pictures somewhere else and then update the url.

BUT, be very very careful with this feature. It will change the update date of the activity if you change it's picture url

<img width="1682" alt="screen shot 2017-09-08 at 7 24 37 pm" src="https://user-images.githubusercontent.com/586992/30234491-89f23532-94cb-11e7-8037-f19a85de1bbc.png">
@cmgordon
