### ISSUE TITLE
gsr and accelerometer data empty + timestamps

### ISSUE THREAD

**Issue by imana97** [ctpc/nucoach-issues#37]
Hi Navi,
1. the GSR and accelerometer data I receive from ms band ios are empty

<img width="619" alt="screen shot 2017-09-07 at 6 54 17 pm" src="https://user-images.githubusercontent.com/586992/30188729-162e2f52-93fe-11e7-9922-53458938fd47.png">

2. timestamps have floating number. any change we send int instead of double numbers?

like 1504824485467.948 becomes 1504824485467

the floating point is not necessary... millisecond precision is enough. and also will be consistent with the android collector.

**Comment by Navarjun** [comment]
Fixed…

**Comment by imana97** [comment]
thanks.
