### ISSUE TITLE
emfit data rows

### ISSUE THREAD

**Issue by imana97** [ctpc/nucoach-issues#38]
Hi, 
just noticed that emfit data does not add row, but update the current row.

it seems like there is only one session ID?

or is that because you don't use it?

<img width="853" alt="screen shot 2017-09-11 at 11 02 34 am" src="https://user-images.githubusercontent.com/586992/30281650-fb39462e-96e0-11e7-93e7-99c4fb571e87.png">

**Comment by imana97** [comment]
@Navarjun I just checked on this, still the same... just updating the row.
did you use emfit after sept 7?

**Comment by Navarjun** [comment]
You can mark it fixed now, Iman

Thanks

**Comment by imana97** [comment]
thanks.
