### ISSUE TITLE
Only 100 simultaneous commands can be sent at once!

### ISSUE THREAD

**Issue by sean369see** [ctpc/nucoach-issues#42]
Please take a look a this if you haven't already?
https://stackoverflow.com/questions/43850161/microsoft-band-2-stops-working-with-unknown-error-only-100-simultaneous-comman

I guess we need to tell participants to restart the band and not just deephealth and the phone.

**Comment by imana97** [comment]
since this is MS band error and we can't do anything about it, I close this issue.
