### ISSUE TITLE
Sort by number of missing replies to surveys

### ISSUE THREAD

**Issue by sean369see** [ctpc/nucoach-issues#54]
![capture](https://user-images.githubusercontent.com/2666708/32804994-05d3cd82-c956-11e7-8dab-d34a980f1bab.PNG)

**Comment by imana97** [comment]
well, this is pretty hard to do. cuz the values are calculated on the fly. I am thinking about changing this to something better.

**Comment by sean369see** [comment]
My idea was just some kind of simple indicator to rank who is the "worst" or most urgently in need of intervention.

**Comment by imana97** [comment]
thanks xuan. so we do that in the daily reports.
