### ISSUE TITLE
delete all scheduled activities

### ISSUE THREAD

**Issue by cmgordon** [ctpc/nucoach-issues#6]
Can you make it an option to delete all scheduled activities for a participant? If they drop out, I need to delete each scheduled activity one by one so that they no longer receive messages. It would be great if I could do this with one click instead. 

Or: delete all scheduled activities between X and Y dates/times.

**Comment by imana97** [comment]
yes, I am going to add a feature in the action plan that is called, terminate action plan. Meaning it will delete every future activity and reminders.

**Comment by imana97** [comment]
on dashboard, actions plans, click action, terminate this action plan.
@cmgordon : PLEASE use CAUTION. This is a beta feature. I would say first try on a dummy action plan.
