### ISSUE TITLE
3 GymCentral changes

### ISSUE THREAD

**Issue by cmgordon** [ctpc/nucoach-issues#71]
- Need to be able to edit a template (or make a copy that I can edit)
- Under "Select an Exercise," each group is expanded. Can they be collapsed? Otherwise, the list will become very long.
- I currently cannot delete any templates. When I click the trash icon, it asks me if I want to delete this template. After I click "yes," the template is still there.

**Comment by imana97** [comment]
I currently cannot delete any templates. When I click the trash icon, it asks me if I want to delete this template. After I click "yes," the template is still there.
@cmgordon: should be fixed. please let me know if it happened again.
