### ISSUE TITLE
Lambda function for coach card modules

### ISSUE THREAD

**Issue by Navarjun** [ctpc/nucoach-issues#73]
I feel there should be a way to request a lambda function from the **coach card/client card**.
This will allow us to request and process data on the lambda, instead of processing all of it on the front-end. It will be really helpful when doing visualisations, right now it takes a while to load the data and then iterate or modify it for visualisation purposes.

**Comment by imana97** [comment]
right, I think you can do that already. If you create a lambda fn with CORS enabled no?

**Comment by imana97** [comment]
Hi, I close this issue as I think we are not doing this anymore right?
