### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by cmgordon** [ctpc/nucoach-issues#9]
I would like to be able to download all of the data collected during the study (e.g. survey responses, daily Misfit data, number of activities completed, messages opened, etc.). How much of this is possible?

**Comment by imana97** [comment]
I would say all of it, but it should be our next milestone.
let's keep this open for now,

@Navarjun , please follow this thread, we need to meet and discuss this.

**Comment by imana97** [comment]
@cmgordon data download should work for survey and antiox photos.
please be patient especially for the survey, it will take a while... (upto 5 minutes sometimes)
